version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app
      APPLICATION_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app